## Summary

summary goes here lol

In [2]:
# Import the wine dataset
import sklearn as the_machine # what is bro learning???
import numpy as np
import pandas as pd

wine_data = the_machine.datasets.load_wine()
wine_df = pd.DataFrame(data=wine_data.data, columns=wine_data.feature_names)
wine_df

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0

In [3]:
#shape of the dataset
shape = np.shape(wine_data.data)
print("Wine Data Shape: ", shape)

#size of data
size = np.size(wine_data.data)
print("Wine Data Size: ", size)

#dimensions of data
dim = np.ndim(wine_data.data)
print("Wine Data Dimensions: ", dim)

Wine Data Shape:  (178, 13)
Wine Data Size:  2314
Wine Data Dimensions:  2

In [4]:
#min, max, average for features and target labels
stats_df = pd.DataFrame(index = ['Minimum', 'Maximum', 'Average'])
for i in range(len(wine_data.feature_names)):
    name = wine_data.feature_names[i]
    stats_df[name] = [
        np.min(wine_df[name]),
        np.max(wine_df[name]),
        np.average(wine_df[name])
    ]
stats_df['target'] = [
    np.min(wine_data.target),
    np.max(wine_data.target),
    np.average(wine_data.target)
]
stats_df

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
Minimum,11.030000,0.740000,1.360000,10.600000,70.000000,0.980000,0.34000,0.130000,0.410000,1.28000,0.480000,1.270000,278.000000,0.000000
Maximum,14.830000,5.800000,3.230000,30.000000,162.000000,3.880000,5.08000,0.660000,3.580000,13.00000,1.710000,4.000000,1680.000000,2.000000
Average,13.000618,2.336348,2.366517,19.494944,99.741573,2.295112,2.02927,0.361854,1.590899,5.05809,0.957449,2.611685,746.893258,0.938202